title = "Best overall pressure profile"
author = "Decent"
notes = "We recommend this pressure profile as the most likely to produce a good espresso in the most varied number of cases. The decreasing pressure will help reduce acidity."
beverage_type = "espresso"
tank_temperature = 0
target_weight = 36
target_volume = 36
target_volume_count_start = 2
legacy_profile_type = "settings_2a"
type = "pressure"
lang = "en"
hidden = false
reference_file = ""
changes_since_last_espresso = ""
version = 2

[[steps]]
name = "preinfusion temp boost"
temperature = 88
sensor = "coffee"
pump = "flow"
transition = "fast"
pressure = 1
flow = 3.5
seconds = 2
volume = 0
weight = 0

[steps.exit]
type = "pressure"
condition = "over"
value = 4

[[steps]]
name = "preinfusion"
temperature = 88
sensor = "coffee"
pump = "flow"
transition = "fast"
pressure = 1
flow = 3.5
seconds = 18
volume = 0
weight = 0

[steps.exit]
type = "pressure"
condition = "over"
value = 4

[[steps]]
name = "forced rise without limit"
temperature = 88
sensor = "coffee"
pump = "pressure"
transition = "fast"
pressure = 8.4
# flow = undefined
seconds = 3
volume = 0
weight = 0

[[steps]]
name = "rise and hold"
temperature = 88
sensor = "coffee"
pump = "pressure"
transition = "fast"
pressure = 8.4
# flow = undefined
seconds = 7
volume = 0
weight = 0

[steps.limiter]
value = 3.5
range = 1

[[steps]]
name = "decline"
temperature = 88
sensor = "coffee"
pump = "pressure"
transition = "smooth"
pressure = 6
# flow = undefined
seconds = 30
volume = 0
weight = 0

[steps.limiter]
value = 3.5
range = 1
